import { DeleteOutlined, DownloadOutlined, EditOutlined, PlusOutlined, ReloadOutlined } from '@ant-design/icons';
import { ModalForm, PageContainer, ProFormDigit, ProFormRadio, ProFormSelect, ProFormText, ProFormTextArea, ProTable } from '@ant-design/pro-components';
import type { ActionType, ProColumns } from '@ant-design/pro-components';
import { App, Drawer, Tag } from 'antd';
import { useRef, useState } from 'react';
import { PermissionButton } from '@/components/PermissionButton'; import { useDict } from '@/hooks/useDict';
import { addDictData, addDictType, deleteDictData, deleteDictTypes, getDictData, getDictType, listDictData, listDictTypes, refreshDictCache, updateDictData, updateDictType } from '@/services/system/dict';
import type { DictDataRecord, DictTypeRecord } from '@/services/system/dict'; import { downloadFile } from '@/utils/download';

export default function DictPage() {
  const { message, modal } = App.useApp(); const typeRef = useRef<ActionType>(); const dataRef = useRef<ActionType>();
  const [selected, setSelected] = useState<React.Key[]>([]); const [dataSelected, setDataSelected] = useState<React.Key[]>([]); const [typeEditing, setTypeEditing] = useState<DictTypeRecord>(); const [dataEditing, setDataEditing] = useState<DictDataRecord>();
  const [typeOpen, setTypeOpen] = useState(false); const [dataOpen, setDataOpen] = useState(false); const [activeType, setActiveType] = useState<DictTypeRecord>(); const [drawerOpen, setDrawerOpen] = useState(false); const normalDict = useDict('sys_normal_disable');
  const openType = async (r?: DictTypeRecord) => { setTypeEditing(r?.dictId ? (await getDictType(r.dictId)).data : { dictName: '', dictType: '', status: '0' }); setTypeOpen(true); };
  const openData = async (r?: DictDataRecord) => { setDataEditing(r?.dictCode ? (await getDictData(r.dictCode)).data : { dictType: activeType!.dictType, dictLabel: '', dictValue: '', dictSort: 0, status: '0', listClass: 'default' }); setDataOpen(true); };
  const typeColumns: ProColumns<DictTypeRecord>[] = [
    { title: '字典编号', dataIndex: 'dictId', search: false }, { title: '字典名称', dataIndex: 'dictName' }, { title: '字典类型', dataIndex: 'dictType', render: (_, r) => <a onClick={() => { setActiveType(r); setDrawerOpen(true); }}>{r.dictType}</a> },
    { title: '状态', dataIndex: 'status', valueType: 'select', valueEnum: Object.fromEntries(normalDict.options.map((i) => [i.value, { text: i.label }])), render: (_, r) => <Tag color={r.status === '0' ? 'success' : 'error'}>{r.status === '0' ? '正常' : '停用'}</Tag> }, { title: '备注', dataIndex: 'remark', search: false }, { title: '创建时间', dataIndex: 'createTime', valueType: 'dateRange', render: (_, r) => r.createTime || '-' },
    { title: '操作', valueType: 'option', render: (_, r) => [<PermissionButton key="e" type="link" permission="system:dict:edit" onClick={() => void openType(r)}>修改</PermissionButton>, <PermissionButton key="l" type="link" permission="system:dict:edit" onClick={() => { setActiveType(r); setDrawerOpen(true); }}>列表</PermissionButton>, <PermissionButton key="d" type="link" danger permission="system:dict:remove" onClick={() => modal.confirm({ title: `确认删除字典「${r.dictName}」？`, onOk: async () => { await deleteDictTypes([r.dictId!]); message.success('删除成功'); typeRef.current?.reload(); } })}>删除</PermissionButton>] }
  ];
  const dataColumns: ProColumns<DictDataRecord>[] = [
    { title: '字典编码', dataIndex: 'dictCode', search: false }, { title: '字典标签', dataIndex: 'dictLabel' }, { title: '字典键值', dataIndex: 'dictValue', search: false }, { title: '字典排序', dataIndex: 'dictSort', search: false },
    { title: '状态', dataIndex: 'status', valueType: 'select', valueEnum: Object.fromEntries(normalDict.options.map((i) => [i.value, { text: i.label }])), render: (_, r) => <Tag color={r.status === '0' ? 'success' : 'error'}>{r.status === '0' ? '正常' : '停用'}</Tag> }, { title: '备注', dataIndex: 'remark', search: false }, { title: '创建时间', dataIndex: 'createTime', search: false },
    { title: '操作', valueType: 'option', render: (_, r) => [<PermissionButton key="e" type="link" permission="system:dict:edit" onClick={() => void openData(r)}>修改</PermissionButton>, <PermissionButton key="d" type="link" danger permission="system:dict:remove" onClick={() => modal.confirm({ title: `确认删除字典数据「${r.dictLabel}」？`, onOk: async () => { await deleteDictData([r.dictCode!]); message.success('删除成功'); dataRef.current?.reload(); } })}>删除</PermissionButton>] }
  ];
  return <PageContainer><ProTable<DictTypeRecord> rowKey="dictId" actionRef={typeRef} columns={typeColumns} rowSelection={{ selectedRowKeys: selected, onChange: setSelected }} request={async ({ current, pageSize, createTime, ...p }) => { const r = await listDictTypes({ ...p, pageNum: current, pageSize, beginTime: createTime?.[0], endTime: createTime?.[1] }); return { data: r.rows, total: r.total, success: r.code === 200 }; }} toolBarRender={() => [
    <PermissionButton key="a" type="primary" icon={<PlusOutlined />} permission="system:dict:add" onClick={() => void openType()}>新增</PermissionButton>, <PermissionButton key="e" icon={<EditOutlined />} permission="system:dict:edit" disabled={selected.length !== 1} onClick={() => void openType({ dictId: Number(selected[0]), dictName: '', dictType: '' })}>修改</PermissionButton>, <PermissionButton key="d" danger icon={<DeleteOutlined />} permission="system:dict:remove" disabled={!selected.length} onClick={() => modal.confirm({ title: `确认删除字典编号「${selected.join(',')}」？`, onOk: async () => { await deleteDictTypes(selected); setSelected([]); message.success('删除成功'); typeRef.current?.reload(); } })}>删除</PermissionButton>, <PermissionButton key="x" icon={<DownloadOutlined />} permission="system:dict:export" onClick={() => void downloadFile('/system/dict/type/export', {}, `dict_${Date.now()}.xlsx`)}>导出</PermissionButton>, <PermissionButton key="r" danger icon={<ReloadOutlined />} permission="system:dict:remove" onClick={async () => { await refreshDictCache(); message.success('刷新成功'); }}>刷新缓存</PermissionButton>]} />
  <ModalForm<DictTypeRecord> title={typeEditing?.dictId ? '修改字典类型' : '添加字典类型'} open={typeOpen} initialValues={typeEditing} modalProps={{ destroyOnClose: true, onCancel: () => setTypeOpen(false) }} onFinish={async (v) => { const d = { ...typeEditing, ...v }; typeEditing?.dictId ? await updateDictType(d) : await addDictType(d); message.success(typeEditing?.dictId ? '修改成功' : '新增成功'); setTypeOpen(false); typeRef.current?.reload(); return true; }}><ProFormText name="dictName" label="字典名称" rules={[{ required: true }]} /><ProFormText name="dictType" label="字典类型" rules={[{ required: true }, { pattern: /^[a-z][a-z0-9_]*$/, message: '请使用小写字母、数字和下划线' }]} /><ProFormRadio.Group name="status" label="状态" options={normalDict.options} /><ProFormTextArea name="remark" label="备注" /></ModalForm>
  <Drawer title={`字典数据 - ${activeType?.dictName || ''}`} width="88%" open={drawerOpen} onClose={() => setDrawerOpen(false)} destroyOnClose><ProTable<DictDataRecord> rowKey="dictCode" actionRef={dataRef} columns={dataColumns} rowSelection={{ selectedRowKeys: dataSelected, onChange: setDataSelected }} request={async ({ current, pageSize, ...p }) => { const r = await listDictData({ ...p, dictType: activeType?.dictType, pageNum: current, pageSize }); return { data: r.rows, total: r.total, success: r.code === 200 }; }} toolBarRender={() => [<PermissionButton key="a" type="primary" icon={<PlusOutlined />} permission="system:dict:add" onClick={() => void openData()}>新增</PermissionButton>, <PermissionButton key="d" danger icon={<DeleteOutlined />} permission="system:dict:remove" disabled={!dataSelected.length} onClick={async () => { await deleteDictData(dataSelected); setDataSelected([]); message.success('删除成功'); dataRef.current?.reload(); }}>删除</PermissionButton>, <PermissionButton key="x" icon={<DownloadOutlined />} permission="system:dict:export" onClick={() => void downloadFile('/system/dict/data/export', { dictType: activeType?.dictType }, `data_${Date.now()}.xlsx`)}>导出</PermissionButton>]} /></Drawer>
  <ModalForm<DictDataRecord> title={dataEditing?.dictCode ? '修改字典数据' : '添加字典数据'} open={dataOpen} initialValues={dataEditing} modalProps={{ destroyOnClose: true, onCancel: () => setDataOpen(false) }} onFinish={async (v) => { const d = { ...dataEditing, ...v }; dataEditing?.dictCode ? await updateDictData(d) : await addDictData(d); message.success(dataEditing?.dictCode ? '修改成功' : '新增成功'); setDataOpen(false); dataRef.current?.reload(); return true; }}><ProFormText name="dictType" label="字典类型" disabled /><ProFormText name="dictLabel" label="数据标签" rules={[{ required: true }]} /><ProFormText name="dictValue" label="数据键值" rules={[{ required: true }]} /><ProFormText name="cssClass" label="样式属性" /><ProFormDigit name="dictSort" label="显示排序" min={0} rules={[{ required: true }]} /><ProFormSelect name="listClass" label="回显样式" options={['default','primary','success','info','warning','danger'].map((v) => ({ label: v, value: v }))} /><ProFormRadio.Group name="status" label="状态" options={normalDict.options} /><ProFormTextArea name="remark" label="备注" /></ModalForm>
  </PageContainer>;
}
